version: '3.9'

services:
  db: # Container de MySQL
    image: mysql:5.7 # FROM mysql:5.7
    volumes:
      - db_data:/var/lib/mysql # VOLUME /var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: felipe
      MYSQL_PASSWORD: felipe
  
  wordpress: # Container de Wordpress
    depends_on:
      - db
    image: wordpress:latest # FROM wordpress:latest
    ports:
      - "8000:80" # PORT 80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: felipe
      WORDPRESS_DB_PASSWORD: felipe
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data: {} # VOLUME /var/lib/mysql