version: '3.9'

services:
  db: # Container de MySQL
    image: mysql:5.7 # FROM mysql:5.7
    volumes:
      - db_data:/var/lib/mysql # VOLUME /var/lib/mysql
    restart: always
    env_file:
      - ./config/db.env
  
  wordpress: # Container de Wordpress
    depends_on:
      - db
    image: wordpress:latest # FROM wordpress:latest
    ports:
      - "8000:80" # PORT 80
    restart: always
    env_file:
      - ./config/wp.env

volumes:
  db_data: {} # VOLUME /var/lib/mysql